### ISSUE TITLE
CloudSession doesn't work

### ISSUE THREAD

**Issue by gohoski** [ErrorGamer2000/scratch3-api#3]
I am trying to create a `CloudSession`, but there is an error talking about `this` being `undefined`.
Error:
```js
        this.send("handshake", {});
             ^

TypeError: Cannot read properties of undefined (reading 'send')
    at sendHandshake (D:\Skretchero-tekst\node_modules\scratch3-api\dist\cloudsession.js:127:14)
    at WebSocket.<anonymous> (D:\Skretchero-tekst\node_modules\scratch3-api\dist\cloudsession.js:47:13)
    at WebSocket.emit (node:events:402:35)
    at WebSocket.setSocket (D:\Skretchero-tekst\node_modules\ws\lib\websocket.js:225:10)
    at ClientRequest.<anonymous> (D:\Skretchero-tekst\node_modules\ws\lib\websocket.js:810:15)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.socketOnData (node:_http_client:527:11)
    at TLSSocket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
```
Code:
```js
const Scratch = require('scratch3-api');
const { username, password } = require('./config.json');

async function main() {
	let session = await Scratch.UserSession.create(username, password);
	let cloud = await session.cloudSession(60*****78);
	/*cloud.on('set', (name, value) => {
		console.log(name, value);
	})*/
}

main();
```

**Comment by illogicalapple** [comment]
me too

**Comment by okawaffles** [comment]
+1 also having this issue.

**Comment by gohoski** [comment]
Will someone fix this?

**Comment by okawaffles** [comment]
Working on a fix now.

**Comment by okawaffles** [comment]
Alright @gohoski @illogicalapple
Try uninstalling this one and installing a modified package I made with `npm i new-scratch3-api` and modify your code to require new-scratch3-api and it should all work.

**Comment by gohoski** [comment]
Hi @okawaffles,
Sorry for the late reply. It works now, thank you!
It would be great if you'll do a pull request.

**Comment by okawaffles** [comment]
All I did was revert back to an old version before typescript. Although, I
did add some custom functions that I can create a pull request for if you’d
like.

**Comment by nexensys** [comment]
@gohoski @okawaffles, and @illogicalapple Hi. I have deprecated `scratch3-api` due to low code quality and bugs. Please switch to `@errorgamer2000/scratch-cloud` instead.
